language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
  - "4"
  # keep for weird Buffer behavior testing
  - "4.2"
  - "0.12"
  - "iojs"
addons:
  code_climate:
    repo_token: 87721cacbe17adea964acc0b042045642028dd38dec212e6ba7d74b0ac4edeeb
after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
